//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienestarU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_actividad_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_actividad_empleado()
        {
            this.tbl_inscripcion = new HashSet<tbl_inscripcion>();
        }
    
        public int id_actividad { get; set; }
        public string lugar_actividad { get; set; }
        public Nullable<System.DateTime> fecha_actividad { get; set; }
        public Nullable<System.TimeSpan> hora_actividad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inscripcion> tbl_inscripcion { get; set; }
    }
}
