//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienestarU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inscripcion
    {
        public int id_inscripcion { get; set; }
        public int id_categoria_usuario { get; set; }
        public int dni_usuario { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string programa_academico { get; set; }
        public string unidad_organizativa { get; set; }
        public int id_actividad { get; set; }
        public int id_torneo { get; set; }
    
        public virtual tbl_actividad_empleado tbl_actividad_empleado { get; set; }
        public virtual tbl_categoria_usuario tbl_categoria_usuario { get; set; }
        public virtual tbl_torneo_interno tbl_torneo_interno { get; set; }
    }
}
