//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienestarU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_asignacion_locker
    {
        public int id_asignacion { get; set; }
        public int id_locker { get; set; }
        public int id_categoria_usuario { get; set; }
        public string dni_usuario { get; set; }
        public string Nombre_usuario { get; set; }
        public string Apellidos_usuario { get; set; }
    
        public virtual tbl_categoria_usuario tbl_categoria_usuario { get; set; }
        public virtual tbl_locker tbl_locker { get; set; }
    }
}
