//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienestarU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_deporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_deporte()
        {
            this.tbl_entrenamiento = new HashSet<tbl_entrenamiento>();
        }
    
        public int id_deporte { get; set; }
        public string nombre_deporte { get; set; }
        public Nullable<int> valor { get; set; }
        public int dni_entrenador { get; set; }
    
        public virtual tbl_entrenador tbl_entrenador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_entrenamiento> tbl_entrenamiento { get; set; }
    }
}
