//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienestarU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entrenamiento
    {
        public int id_entrenamiento { get; set; }
        public int id_deporte { get; set; }
        public string horario { get; set; }
        public string lugar { get; set; }
    
        public virtual tbl_deporte tbl_deporte { get; set; }
    }
}
